# This is a basic workflow to help you get started with Actions

name: Deploy site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# env:
#   REMOTE: cbdwebdev/cbdwebdev.github.io.git
#   DEST: public
#   TOKEN: ${{ secrets.TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        
#       - name: 🚀 Build and deploy
#         uses: victoriadrake/hugo-remote@master
        
      - name: 🚀 Build and deploy
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: v0.72.0-ext
          TARGET_REPO: cbdwebdev/cbdwebdev.github.io
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: cbdcompanies.com
          GITHUB_ACTOR: cbdwebdev
