name: Deploy site

on:
    push:
        branches: [master]

env:
    REMOTE: cbdwebdev/cbdwebdev.github.io.git
    DEST: public
    TOKEN: ${{ secrets.TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Build TinaCMS
              env:
                TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
                TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
              run: pnpm build

            # TODO deploy to other repo or gh-pages branch
