name: Deploy site

on:
    push:
        branches: [main]

env:
    REMOTE: cbdwebdev/cbdwebdev.github.io.git
    DEST: public
    TOKEN: ${{ secrets.TOKEN }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                version: 8.10.5
                run_install: true

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2.6.0
              with:
                hugo-version: 0.121.1
                extended: true

            - name: Build TinaCMS
              env:
                NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
                TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
              run: pnpm build

            - name: GitHub Branch Deployer
              uses: nicholasgriffintn/github-branch-deployment-action@1.0.0
              with:
                # Destination branch to push changes
                BRANCH: gh-pages
                # Directory to push from. Defaults to root
                FOLDER: public
